name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rustfmt:
    name: Formatting (rustfmt)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - name: Rustfmt Check
        uses: clechasseur/rs-fmt-check@v2.0.1

  clippy:
    name: Linting (clippy)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - name: Set up cache
        uses: Swatinem/rust-cache@v2
        
      - name: Run clippy
        uses: clechasseur/rs-clippy-check@v3.0.1
        with:
          args: --all-features -- -Dwarnings

  nextest:
    name: Tests (nextest)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest 

      - name: Set up cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run:
          cargo build

      - name: Run nextest
        run:
          cargo nextest run --all-features --all-targets --profile=ci --no-fail-fast

      - name: Parse error locations
        uses: mikefarah/yq@master
        if: always()
        with:
          cmd: yq -i 'with(.testsuites.testsuite.testcase; .[] |= with(select(.failure != null) | .failure; (."+content" | capture("(?s)panicked at (?P<file>[^:]+):(?P<line>\d+):\d+:\n(?P<message>.*)")) as $match | ."+@file" = $match.file | ."+@line" = $match.line | ."+@message" = $match.message))' target/nextest/ci/junit.xml

      - name: Upload results to GitHub
        uses: mikepenz/action-junit-report@v4.0.3
        if: always()
        with:
          report_paths: target/nextest/ci/junit.xml
          annotate_only: true
